install.packages("devtools")
install.packages("DescTools")
install.packages("tidyverse")
# install.packages("dplyr")
# install.packages("readr")
# install.packages("ggplot2")
# install.packages("tidyr")
# install.packages("purrr")
install.packages("ggvis")
install.packages("lubridate")
install.packages("ada")
install.packages("animation")
install.packages("caret")
install.packages("corrplot")
install.packages("data.table")
install.packages("DiagrammeR")
install.packages("gam")
install.packages("gbm")
install.packages("gdata")
install.packages("ggExtra")
install.packages("glmnet")
install.packages("gplots")
install.packages("gtable")
install.packages("igraph")
install.packages("visNetwork")
install.packages("knitr")
install.packages("MASS")
install.packages("mboost")
install.packages("microbenchmark")
install.packages("neuralnet")
install.packages("nnet")
install.packages("randomForest")
install.packages("rmarkdown")
install.packages("ROCR")
install.packages("rvest")
install.packages("shiny")
install.packages("swirl")
install.packages("manipulate")
install.packages("pROC")
install.packages("zoo")
install.packages("e1071")
install.packages("broom")
install.packages("questionr")

install.packages("RODBC") # install after xcode / command line tools

